### PR TITLE
Test L2 spell

### PR DESCRIPTION
**Pull request by krzkaczor**
L2 gas limit: `3000000`

Deployed on testnet kovan: `0xC88e0cDAA48FA8cA12212b157fdee617be4cBD70`

Deployed on mainnet: https://optimistic.etherscan.io/address/0x71d75C3D100D14d4db0cE7a83d0De48ecEC32D19#code

### CODE REVIEW

**Review by hexonaut — APPROVED** [review]
The spell looks fine to me. Are you planning to actually execute this on mainnet? I think a fork should be sufficient, and in fact we probably want some sort of fork / test suite first before executing any spells on Optimism. Tossing out spells blindly is a dangerous game even for something as simple as this.

**Comment by krzkaczor** [comment]
To clarify - it's not about testing contract's permissions (auth's rely) these are easy to verify with scripts. This is more about testing if L1GovernanceRelay & L2GovernanceRelay are setup correctly and messages are relyed correctly. The problem is that there is no easy way to run optimism in a forked mode.

**Comment by hexonaut** [comment]
Right, I guess there is a trade off with some slight uncertainty executing a spell without tests and redeploying DAI asap if there is some bug preventing us from executing spells on L2. If there is no easy path to get a fork soon then I guess it makes to do a test run. The code is dead simple, so it's probably worthwhile to do the test run sooner rather than later.

**Review by hexonaut — APPROVED** [review]
LGTM after linter fixed

**Pull request closed without merging**
